### ISSUE TITLE
Bug: Unsuccessful R2modman install

### ISSUE THREAD

**Issue by Austin-Flowers** [joeyparrish/pokeheim#1]
Installed on a new R2modman profile. 
When starting the game, the initial start menu has a large white box over it and no Pokeheim logo.
New character, new seed. Intro only loads the words [Pokehim_Intro] (or something like that). All of Hugins prompts are also within brackets and the compendium doesn't update with the actual tutorial information.

Overall, not loaded correctly. I don't see a config file being created, which could be the issue.

**Comment by joeyparrish** [comment]
I found the problem.  R2modman seems to flatten out the contents of the Pokeheim zip file, which breaks the mod.

The zip from Thunderstore looks like this if you download it manually:

```
Archive:  /home/joey/Downloads/Pokeheim-Pokeheim-1.0.3.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2022-06-15 10:33   Pokeheim/
        0  2022-06-15 10:33   Pokeheim/Assets/
     2720  2022-06-15 10:33   Pokeheim/Assets/Sort icon.png
        0  2022-06-15 10:32   Pokeheim/Assets/Translations/
        0  2022-06-15 10:32   Pokeheim/Assets/Translations/Portuguese_Brazilian/
      185  2022-06-15 10:32   Pokeheim/Assets/Translations/Portuguese_Brazilian/balls.json
       68  2022-06-15 10:32   Pokeheim/Assets/Translations/Portuguese_Brazilian/bosses.json
     2781  2022-06-15 10:32   Pokeheim/Assets/Translations/Portuguese_Brazilian/giovanni.json
      176  2022-06-15 10:32   Pokeheim/Assets/Translations/Portuguese_Brazilian/stats.json

... [snip] ...

   717293  2022-06-15 10:33   Pokeheim/Assets/Logo.png
   134144  2022-06-15 10:33   Pokeheim/Pokeheim.dll
     4519  2022-06-15 10:33   README.md
    51981  2022-06-15 10:33   icon.png
      315  2022-06-15 10:33   manifest.json
---------                     -------
  4960238                     96 files
```

What you get from r2modman looks like this:

```
~/.config/r2modmanPlus-local/Valheim/profiles/Default/BepInEx/plugins/Pokeheim-Pokeheim:
 balls.json                 'Pokedex icon.png'              riding.json
 bosses.json                 Pokeheim.dll                  'Skill icon.png'
 giovanni.json               PremadeIcon-Bat.png           'Sort icon.png'
 icon.png                    PremadeIcon-BlobElite.png      stats.json
 Inhabited-overlay.png       PremadeIcon-fallback.png      'Super monster ball.png'
 intro.json                  PremadeIcon-Fenring.png       'Super monster ball texture.png'
 language.json               PremadeIcon-Ghost.png          tips.json
 Logo.png                    PremadeIcon-GoblinShaman.png   tutorials.json
 Main-Menu.mp3               PremadeIcon-Greyling.png      'Ultra monster ball.png'
 manifest.json               PremadeIcon-TentaRoot.png     'Ultra monster ball texture.png'
'Monster ball.png'           PremadeIcon-Ulv.png            wardrobe.json
'Monster ball texture.png'   README.md
```

This is obviously super broken.  Not only can the mod not find its files where it expects, but flattening out the `Translations` folder overwrites files with the same name in different folders.

I don't understand why R2modman would do this.

**Comment by joeyparrish** [comment]
I tried to test Thunderstore Mod Manager behavior to compare, but I don't have Windows and it failed to install on Linux under wine.

**Comment by joeyparrish** [comment]
Can't make Vortex run on Linux for comparison, either.

**Comment by joeyparrish** [comment]
@Fllowers, are you on Linux or Windows?

**Comment by Craby4GitHub** [comment]
I also notice the same issues, but I am not using R2modman, just a fresh profile with Thunderstore Mod Manager. 

Looking at the BepInEx window, I have this error:
[Warning: Unity Log] 06/16/2022 07:04:40: Missing audio clip in music respawn
[Error  :Pokeheim.MusicMods] Failed to load clip from C:\Users\UserName\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\POKEMON\BepInEx\plugins\Pokeheim/Assets/Main-Menu.mp3: HTTP/1.1 404 Not Found
[Error  :Pokeheim.MusicMods+CustomMusic_Patch] Failed to load music override: menu

I navigated to the plugin folder location, but there is not a Pokeheim folder, but a Pokeheim-Pokeheim folder with all the content, including the Main-Menu.mp3. Also, due to Windows, the file path would need backslashes in the rest of the file path. Perhaps that's why the assets arent loading in-game also?

**Comment by joeyparrish** [comment]
It seems to be due to undocumented expectations from the mod managers for the file structure in the zip.  I have a fix that works in r2modman, which I'll be publishing shortly on Thunderstore and Nexus.  I'll update here when it's fully published.  Hopefully the same fix works for Thunderstore.  Since the symptoms are the same, I'm hopeful that the same fix will work, too.

**Comment by joeyparrish** [comment]
The new version (1.0.4) is now showing up in r2modman.  Please try again in r2modman or Thunderstore Mod Manager.  Sorry for the trouble, and thanks for your help!
